replicaCount: 1

image:
  repository: ghcr.io/davidnet-net/social
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: social.davidnet.net
  ingressClass: traefik
